Installer and init script are working

diff --git a/Supervisord/supervisord b/Supervisord/supervisord
--- a/Supervisord/supervisord
+++ b/Supervisord/supervisord
@@ -16,20 +16,17 @@
 ### END INIT INFO
 
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/bin/supervisord
-DAEMON_OPTS="-c /etc/supervisord.conf"
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
 NAME=supervisord
 DESC="Supervisor daemon"
+LOGDIR=/var/log/$NAME
+PIDFILE=/var/run/$NAME/$NAME.pid
+DODTIME=5
+DAEMON=/usr/bin/$NAME
+DAEMON_OPTS="-c /etc/$NAME.conf"
 
 test -x $DAEMON || exit 0
 
-LOGDIR=/var/log/supervisord
-PIDFILE=/var/run/$NAME.pid
-DODTIME=5                   # Time to wait for the server to die, in seconds
-							# If this value is set too low you might not
-							# let some servers to die gracefully and
-							# 'restart' will not work
 
 # Include supervisor defaults if available
 if [ -f /etc/default/supervisor ] ; then
@@ -73,7 +70,7 @@ force_stop() {
 			kill -9 $pid
 			[ -n "$DODTIME" ] && sleep "$DODTIME"s
 			if running ; then
-				echo "Cannot kill $LABEL (pid=$pid)!"
+				echo "Cannot kill $DESC (pid=$pid)!"
 				exit 1
 			fi
 		fi
@@ -85,27 +82,26 @@ force_stop() {
 case "$1" in
   start)
 	echo -n "Starting $DESC: "
-	start-stop-daemon --start --quiet --pidfile $PIDFILE \
-		--exec $DAEMON -- $DAEMON_OPTS
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
 	test -f $PIDFILE || sleep 1
 		if running ; then
-			echo "$NAME."
+			echo "Success"
 		else
-			echo " ERROR."
+			echo -e "\033[31mError\033[0m"
 		fi
 	;;
   stop)
 	echo -n "Stopping $DESC: "
 	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
-	echo "$NAME."
+	echo "Success"
 	;;
   force-stop)
 	echo -n "Forcefully stopping $DESC: "
 		force_stop
 		if ! running ; then
-			echo "$NAME."
+			echo "Success"
 		else
-			echo " ERROR."
+			echo -e "\033[31mError\033[0m"
 		fi
 	;;
   #reload)
@@ -127,22 +123,17 @@ case "$1" in
 	#	just the same as "restart" except that it does nothing if the
 	#   daemon isn't already running.
 	# check wether $DAEMON is running. If so, restart
-	start-stop-daemon --stop --test --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON \
-	&& $0 restart \
-	|| exit 0
+	start-stop-daemon --stop --test --quiet --pidfile $PIDFILE --exec $DAEMON && $0 restart || exit 0
 	;;
   restart)
 	echo -n "Restarting $DESC: "
-	start-stop-daemon --stop --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON
+	start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON
 	[ -n "$DODTIME" ] && sleep $DODTIME
-	start-stop-daemon --start --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
 	echo "$NAME."
 	;;
   status)
-	echo -n "$LABEL is "
+	echo -n "$DESC is "
 	if running ;  then
 		echo "running"
 	else
